// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CWmisc_mmap
List CWmisc_mmap(std::string path);
RcppExport SEXP Wmisc_CWmisc_mmap(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(CWmisc_mmap(path));
    return rcpp_result_gen;
END_RCPP
}
// CWmisc_munmap
void CWmisc_munmap(List fdVec);
RcppExport SEXP Wmisc_CWmisc_munmap(SEXP fdVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type fdVec(fdVecSEXP);
    CWmisc_munmap(fdVec);
    return R_NilValue;
END_RCPP
}
// CWmisc_nextToken
List CWmisc_nextToken(IntegerVector currentPtr, IntegerVector delims);
RcppExport SEXP Wmisc_CWmisc_nextToken(SEXP currentPtrSEXP, SEXP delimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type currentPtr(currentPtrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delims(delimsSEXP);
    rcpp_result_gen = Rcpp::wrap(CWmisc_nextToken(currentPtr, delims));
    return rcpp_result_gen;
END_RCPP
}
// CWmisc_validPtr
bool CWmisc_validPtr(IntegerVector map, IntegerVector target, int offset);
RcppExport SEXP Wmisc_CWmisc_validPtr(SEXP mapSEXP, SEXP targetSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type map(mapSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(CWmisc_validPtr(map, target, offset));
    return rcpp_result_gen;
END_RCPP
}
