# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

strHead <- function(s) {
    .Call('Wmisc_strHead', PACKAGE = 'Wmisc', s)
}

strHeadLower <- function(s) {
    .Call('Wmisc_strHeadLower', PACKAGE = 'Wmisc', s)
}

strTail <- function(s) {
    .Call('Wmisc_strTail', PACKAGE = 'Wmisc', s)
}

strTake <- function(s, n) {
    .Call('Wmisc_strTake', PACKAGE = 'Wmisc', s, n)
}

strDrop <- function(s, n) {
    .Call('Wmisc_strDrop', PACKAGE = 'Wmisc', s, n)
}

CWmisc_mmap <- function(path) {
    .Call('Wmisc_CWmisc_mmap', PACKAGE = 'Wmisc', path)
}

CWmisc_munmap <- function(fdVec) {
    invisible(.Call('Wmisc_CWmisc_munmap', PACKAGE = 'Wmisc', fdVec))
}

CWmisc_nextToken <- function(currentPtr, delims) {
    .Call('Wmisc_CWmisc_nextToken', PACKAGE = 'Wmisc', currentPtr, delims)
}

CWmisc_validPtr <- function(map, target, offset) {
    .Call('Wmisc_CWmisc_validPtr', PACKAGE = 'Wmisc', map, target, offset)
}

